### ISSUE TITLE
"Copy the mapbox token at this link" goes to t.uber.com

### ISSUE THREAD

**Issue by austinhyde** [uber/kepler.gl#218]
**Describe the bug**
The README steps describe getting a mapbox token from a tuber link/onelogin, it should probably not say that on the public page ;)

**To Reproduce**
Click the link in the README

**Expected behavior**
Not have an internal link

**Comment by heshan0131** [comment]
Thanks for pointing this out. We are using our own mapbox token to host the demo website. Only Uber developers are allowed to deploy the website at the moment. The link to token is an alias, it sits behind uber's login system so that only Uber developers can access it.

I will revise the wording to make it more clear.

**Comment by heshan0131** [comment]
https://github.com/uber/kepler.gl/pull/219
