### ISSUE TITLE
Missing ExportMap option in local instalation

### ISSUE THREAD

**Issue by TomekPro** [uber/kepler.gl#457]
Hi,
I installed kepler locally (Windows 10) and tried to export the map. To my suprise this option is missing whereas on kepler.gl I see it:

Local:
![image](https://user-images.githubusercontent.com/49069202/55237971-a9f92d00-5233-11e9-848e-c0af745d935e.png)

Kepler.gl:
![image](https://user-images.githubusercontent.com/49069202/55238005-bda49380-5233-11e9-974a-4584151fc7b8.png)

Any idea?

Thanks

**Comment by macrigiuseppe** [comment]
Hi @TomekPro,
The reason why you are seeing those features in the demo web site is because the Demo website is a special case of using Kepler.gl with extra features.

I see you have integrated Kepler.gl in your own app based on your url.

If you try to run Kepler.gl example demo-app you will be able to see export map and save share url functionalities.

**Comment by TomekPro** [comment]
Thanks @macrigiuseppe it works! :)
